version: '3.1'

services:
  db:
    image: postgres:12-alpine
    container_name: postgres12
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
